name: "Test"
on:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "1.21.0-9.1.pre"
          channel: "beta"
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter test
      - run: flutter build web
